### ISSUE TITLE
v14.1 broken path for tailwindcss-data

### ISSUE THREAD

**Issue by browniefed** [Arthie/tailwindcssinjs#12]
```
error - ./node_modules/@tailwindcssinjs/macro/lib/tailwindcssinjs.js:9:0
Module not found: Can't resolve '../../tailwindcss-data/lib/utilities'
```

After upgrading from v13 to v14 now getting this coming from macros

**Comment by browniefed** [comment]
Closing this, not totally certain what is happening. Likely something weird with my config. I got it re-working but not certain why ha

**Comment by narze** [comment]
I encountered the same problem (using next.js)

```
ready - started server on http://localhost:3000
info  - Using external babel configuration from /Users/narze/Code/redacted/.babelrc
event - compiled successfully
event - build page: /
wait  - compiling...
error - ./pages/index.tsx
Error: /Users/narze/Code/redacted/pages/index.tsx: Cannot find module '../../tailwindcss-data/lib/utilities'
Require stack:
- /Users/narze/Code/redacted/node_modules/@tailwindcssinjs/macro/lib/tailwindcssinjs.js
- /Users/narze/Code/redacted/node_modules/@tailwindcssinjs/macro/lib/macro.js
- /Users/narze/Code/redacted/node_modules/babel-plugin-macros/dist/index.js
- /Users/narze/Code/redacted/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/narze/Code/redacted/node_modules/@babel/core/lib/config/files/index.js
- /Users/narze/Code/redacted/node_modules/@babel/core/lib/index.js
- /Users/narze/Code/redacted/node_modules/next/dist/compiled/babel-loader/index.js
- /Users/narze/Code/redacted/node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
- /Users/narze/Code/redacted/node_modules/loader-runner/lib/loadLoader.js
- /Users/narze/Code/redacted/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/narze/Code/redacted/node_modules/next/node_modules/webpack/lib/NormalModule.js
- /Users/narze/Code/redacted/node_modules/next/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/narze/Code/redacted/node_modules/next/node_modules/webpack/lib/Compiler.js
- /Users/narze/Code/redacted/node_modules/next/node_modules/webpack/lib/webpack.js
- /Users/narze/Code/redacted/node_modules/next/node_modules/@next/react-dev-overlay/lib/middleware.js
- /Users/narze/Code/redacted/node_modules/next/dist/server/hot-reloader.js
- /Users/narze/Code/redacted/node_modules/next/dist/server/next-dev-server.js
- /Users/narze/Code/redacted/node_modules/next/dist/server/next.js
- /Users/narze/Code/redacted/node_modules/next/dist/server/lib/start-server.js
- /Users/narze/Code/redacted/node_modules/next/dist/cli/next-dev.js
- /Users/narze/Code/redacted/node_modules/next/dist/bin/next
event - build page: /next/dist/pages/_error
wait  - compiling...
```

**Comment by browniefed** [comment]
@narze delete .next folder and run dev again.

**Comment by clement-buchart** [comment]
I had the same issue, for me it was because of `typescript-tailwindcssinjs-plugin` that caused `@tailwindcssinjs/tailwindcss-data` to stay in an older version.

```
❯ yarn list | grep tailwind
├─ @tailwindcss/custom-forms@0.2.1
├─ @tailwindcss/typography@0.2.0
├─ @tailwindcss/ui@0.6.2
│  ├─ @tailwindcss/custom-forms@^0.2.1
│  ├─ @tailwindcss/typography@^0.2.0
├─ @tailwindcssinjs/class-composer@0.17.0
├─ @tailwindcssinjs/macro@0.17.0
│  ├─ @tailwindcssinjs/class-composer@^0.17.0
│  ├─ @tailwindcssinjs/tailwindcss-data@^0.17.0
│  ├─ @tailwindcssinjs/tailwindcss-data@0.17.0
├─ @tailwindcssinjs/tailwindcss-data@0.9.1
├─ emotion-tailwind-preflight@1.2.0
├─ tailwindcss@1.9.6
├─ typescript-tailwindcssinjs-plugin@0.3.2
│  ├─ @tailwindcssinjs/class-composer@^0.9.0
│  ├─ @tailwindcssinjs/class-composer@0.9.0
│  ├─ @tailwindcssinjs/tailwindcss-data@0.9.1
```
Worked around by removing the typescript plugin.

@Arthie the [npm page for the typescript plugin](https://www.npmjs.com/package/typescript-tailwindcssinjs-plugin) is returning a 404 : has it been discontinued ?

**Comment by Arthie** [comment]
Hello @clement-buchart, I am currently figuring out how to rebrand @tailwindcssinjs (see #13). I have removed the `typescript-tailwindcssinjs-plugin` since it was due for an update and plan on deprecating the other packages for a while. The typescript plugin will be updated and re-released soon using a different name.

**Comment by clement-buchart** [comment]
Understood, thanks for the update 🙂
